### ISSUE TITLE
Action maker is broken

### ISSUE THREAD

**Issue by time-killer-games** [RobertBColton/ActionMaker#3]
Actually, this is just a complaint that you have been ignoring me for a week over something that fundies does to you every few minutes that i do rather scarcely, and that is call you a name out of jest, where as fundies is dead serious when he calls you names, I am not. I'm not sure why you are picking on me of all people, but if you don't respond after seeing this, I'm going to flat out give up on contacting you and posting stuff like this.

**Comment by RobertBColton** [comment]
I have and will defend myself against anybody who attacks me. I have done literally nothing to anybody, so please stop posting stuff like this everywhere. Post it one more time and I will advocate for a temp ban.

**Comment by time-killer-games** [comment]
I can advocate for a temp ban for you, when put in correct context and not going by your misinformed perspective that refuses to have a pinch of understanding. But whatever, I already said I would stop, so your threats are just making you look bad in the long run.

**Comment by time-killer-games** [comment]
1) I was not attacking you, I was joking, we've been over this. You got pissed at me over literally nothing.
2) I realise it was my fault I posted this, but any chance you could delete it?
